version: 2.1

jobs:
  deploy_pipeline:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: 🔧 Step 1 - Setup environment
          command: echo "Pretend we're setting up the environment"

      - run:
          name: 🧪 Step 2 - Run tests
          command: echo "Pretend we're running tests"

      - run:
          name: 🚀 Step 3 - Deploy to staging
          command: echo "Pretend we're deploying to staging"

      - run:
          name: ✅ Step 4 - Finish
          command: echo "All done!"

workflows:
  version: 2
  Snorkel-Deploy-Pipeline:
    jobs:
      - deploy_pipeline
